### ISSUE TITLE
設定ファイルパス指定

### ISSUE THREAD

**Issue by kmuto** [yseto/sabatrapd#14]
systemd永続サービス化を考えると、argsでyaml指定がやはりほしくなりそうです。
あと、/usr/local/etc/直下などに設定YAML置くなら「sabatrapd.yaml」とかのほうがいいのかなと思いました。

拡張子yaml/yml論争というのもあって、Re:VIEWはymlにしたりしましたが、@yseto は.yaml派なかんじです？

**Comment by yseto** [comment]
argsでのyaml指定は必要だと思っています。それに手をつけていないのは、他のオプションなど必要になることがわかった時点でまとめて書こうかと思っていたのでした。

拡張子については特段のこだわりは持っていないので、現段階での変更（サンプルやデフォルトのファイル名など）は許容できると考えています。
