### ISSUE TITLE
snmptrap %sを変えたい

### ISSUE THREAD

**Issue by kmuto** [yseto/sabatrapd#16]
https://github.com/yseto/sabatrapd/blob/df65ed72f7e9a79db00d2b53806d2ac544fdd309/notification/queue.go#L68

カスタマイズできるといいかなと思ったけどテンプレート化は面倒な気もするので、`sabatrapd %s`でしょうかね。

**Comment by yseto** [comment]
テンプレート化するのはちょっと激しそうですね。以下のような方法はどうでしょうか
- デフォルトの値を変更する。
- 設定ファイルに送信元アドレス単位で任意の名前を記入できるようにする

**Comment by kmuto** [comment]
なるほど、すごい。前者だけでも十分ですー
