### ISSUE TITLE
プロキシサーバ設定

### ISSUE THREAD

**Issue by kmuto** [yseto/sabatrapd#17]
`HTTPS_PROXY` 付けてね、でいいでしょうかね。
mackerel-agentのコードを見ると設定ファイルから拾ってsetenvしたりはしている模様。

(テストが微妙に面倒くさめ)

**Comment by yseto** [comment]
プロキシサーバの設定は、環境変数で良いと思います。
今のところ、`HTTPS_PROXY` については、[Goのドキュメント](https://go.dev/doc/go1.16#:~:text=The%20ProxyFromEnvironment%20function%20no%20longer%20returns%20the%20setting%20of%20the%20HTTP_PROXY%20environment%20variable%20for%20https%3A//%20URLs%20when%20HTTPS_PROXY%20is%20unset.) にある通りの関数由来の挙動になっているはずです。

**Comment by kmuto** [comment]
READMEでproxyの説明に代えました
