### ISSUE TITLE
コード整理

### ISSUE THREAD

**Issue by yseto** [yseto/sabatrapd#3]
- レポジトリ名を整理する
- パッケージも整理する
- READMEも整理する

**Comment by kmuto** [comment]
リポジトリ名はdoneですね!

パッケージについては、ファイル名や変数名などを少し調整でしょうか。main + libにして、1文字変数系のももうちょっと内容を表すものにするとかですかね。

READMEは私のほうで書いてみましょうか。

**Comment by yseto** [comment]
パッケージ整理は、一旦私のほうで進めてみようと思います。

> READMEは私のほうで書いてみましょうか。

お願いできると大変助かります。

**Comment by yseto** [comment]
コード整理の予定

- 文字コード関連のパッケージ作成 #8
- 文字コード関連のパッケージへの切り替え、smi、configをパッケージにしておく
- 通知処理をパッケージとして切り出す
- テンプレート処理をパッケージとして切り出す

**Comment by yseto** [comment]
コード整理、手元にある変更すべて出させていただきました :bow:

**Comment by kmuto** [comment]
READMEも入った #20 :tada:
