### ISSUE TITLE
チェック監視結果をWarningでなくCriticalなどのレベルでも送りたい

### ISSUE THREAD

**Issue by kmuto** [yseto/sabatrapd#32]
現在の実装ではWarningのみを送るようにしているが、Trap内容によってはCriticalで出したいこともありそう。

- シンプルにはフラグ1つで全体としてWarning/Criticalを切り替える
- がんばるならidentエントリにformatのほかにアラートレベルを設定できるようにする(デフォルトはwarningのままとして、warning/critical/unknown/okを取れるようなものを用意する?)

**Comment by yseto** [comment]
全てがCritical になるとも思いづらいので、個別に、criticalの状態を増やすでしょうか。

```diff
   - ident: .1.3.6.1.6.3.1.1.5.3
     format: '{{ addr }} port {{ read "IF-MIB::ifIndex" }} is linkdown'
+    critical: true
```

> デフォルトはwarningのままとして、warning/critical/unknown/okを取れるようなものを用意する?

できなくはないけれど...Warning になったものを OK にする対を作り込むのは大変（たぶんアドレスとMIBがキーになる。それらを管理する仕組みも必要になるでしょう）なので、Warning / Critical / Unknown 止まりかな...

```diff
   - ident: .1.3.6.1.6.3.1.1.5.3
     format: '{{ addr }} port {{ read "IF-MIB::ifIndex" }} is linkdown'
+   alert-level: critical # warning or critical, unknown. default: warning
```

**Comment by kmuto** [comment]
alert-level: critical|warning|unknown に :+1:
